package com.swp.springboot.dao;

import com.swp.springboot.modal.vo.UserVo;
import com.swp.springboot.modal.vo.UserVoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserVoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbg.generated Thu Oct 25 14:13:54 CST 2018
     */
    long countByExample(UserVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbg.generated Thu Oct 25 14:13:54 CST 2018
     */
    int deleteByExample(UserVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbg.generated Thu Oct 25 14:13:54 CST 2018
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbg.generated Thu Oct 25 14:13:54 CST 2018
     */
    int insert(UserVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbg.generated Thu Oct 25 14:13:54 CST 2018
     */
    int insertSelective(UserVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbg.generated Thu Oct 25 14:13:54 CST 2018
     */
    List<UserVo> selectByExample(UserVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbg.generated Thu Oct 25 14:13:54 CST 2018
     */
    UserVo selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbg.generated Thu Oct 25 14:13:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserVo record, @Param("example") UserVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbg.generated Thu Oct 25 14:13:54 CST 2018
     */
    int updateByExample(@Param("record") UserVo record, @Param("example") UserVoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbg.generated Thu Oct 25 14:13:54 CST 2018
     */
    int updateByPrimaryKeySelective(UserVo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbg.generated Thu Oct 25 14:13:54 CST 2018
     */
    int updateByPrimaryKey(UserVo record);
}